### PR TITLE
Work/jamesd/apprenticeship scheme

### PR DESCRIPTION
**Pull request by dingjimmy**
1st draft. Comments and suggestions please. :)

### CODE REVIEW

**Review by KarenFarrell36 — COMMENTED** [review]
There are a couple of typos - I've highlighted in bold :

During the placement, the Makers course framework **ised** alongside the AM Progression Framework to provide apprentices with a holistic learning experience.

Throughout the placement period, apprentices build-up a portfolio of evidence that goes towards the **final a** final **Assesment** stage that is undertaken after completion of the placement.

**Review by KarenFarrell36 — COMMENTED** [review]
Should this be September 2023?

!!! Warning "WIP Notice - **September 2024**" Not all Duties have been mapped to date. Updates are being made and published as soon as they are ready.

**Review by KarenFarrell36 — COMMENTED** [review]
Typos in bold

To help **faciliate** communication between an apprentice engineer, their Manager and Makers, AM **Enginering** Competencies (as defined in our matrix of **competancies**) are mapped to Occupational Duties (part of the Makers course).

**Review by edwardearle — CHANGES_REQUESTED** [review]
I'm not sure if this needs to be in the playbook. Is there a specific need you have identified for this?

It seems too early to be stating that we have created this partnership with Makers, as we haven't yet made a commitment to continuing with them if/when we decide to bring in new apprentices.

If this is designed as a resource for external use, I think we can part it until we near the time we want to commence this again. If it is designed as a guide for internal use, then perhaps it belongs in a training guide somewhere, maybe even the knowledgebase,.

**Pull request closed without merging**
